/**
 * Hand-authored sample analyses used for development, testing, and preset input chips.
 * These are not generated by the LLM - they are manually written ground-truth examples.
 */

/** sample_1: Clean dual-blocker tension - happy path */
export { sample_1 } from '$lib/samples/sample-1';

/** sample_2: Emotional inaction loop - recommended for UI development */
export { sample_2 } from '$lib/samples/sample-2';

/** sample_3: False contrast / self-imposed constraint */
export { sample_3 } from '$lib/samples/sample-3';

/** sample_4: Dense multi-blocker chain - stress test for graph and insight rail */
export { sample_4 } from '$lib/samples/sample-4';

/** sample_5: Minimal extraction - degraded state / failure case */
export { sample_5 } from '$lib/samples/sample-5';
